version: '3'

services:

  db:
    image: postgres
    ports:
      -"5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  minio-s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: spoton
      MINIO_SECRET_KEY: spoton

  ingest:
    depends_on:
      - db
      - minio-s3
    build:
      context: .
